using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BP.Instructions
{
    public class SectionInstructions
    {
        public List<InstructionItem> instructionItems = new List<InstructionItem>()
        {
            new InstructionItem(){
                section ="Executive Summary",
                instruction ="An executive summary is a short document or section of a document, produced for business purposes, that summarizes a longer report or proposal or a group of related reports in such a way that readers can rapidly become acquainted with a large body of material without having to read it all. It usually contains a brief statement of the problem or proposal covered in the major document(s), background information, concise analysis and main conclusions.\nThink of an executive summary as being a lot like a pitch, but with constraints. A good summary sells the rest of the plan, but it can’t be just a hard sell—it has to actually summarize the plan. Readers expect it to cover your business, product, market, and financial highlights, at the very least."
            },
            new InstructionItem(){
                section ="Financial Summary",
                instruction ="This is a summary of your financial statement. For example:\n\n• How fast is the business expected to grow?\n• What is the total investment required for the business setup?\n• Are you growing slowly and producing profits?\nIf you followed the Tasks order, you have probably already completed all the data entries.\n\nAdditional Detail\nAnother option is to summarize your financial plan in a more general way. This option fits when your financial plan is a significant piece of your expansion or your new business start-up, either because it involves new investment, business expenditures, or a change in the way you do business with accounts receivable, or payables, or stock. For example:\n If you are planning to grow your service business and finance growth by increasing fees, that might be an element of a new financial plan.\nA new long-term loan or major change in your short-term borrowing might also be part of a plan, even if these items don't show up clearly in the financial charts and tables that follow in the printed version."
            },
            new InstructionItem(){
                section ="Financial Statement",
                instruction ="Financial statements are written records that convey the business activities and the financial performance of a company. Financial statements are often audited by government agencies, accountants, firms, etc. to ensure accuracy and for tax, financing, or investing purposes.\nInvestors and financial analysts rely on financial data to analyze the performance of a company and make predictions about its future direction of the company's stock price. One of the most important resources of reliable and audited financial data is the annual report, which contains the firm's financial statements."
            },
            new InstructionItem(){
                section ="Competitive Edge",
                instruction ="What is a competitive advantage and why should it matter to you? Competitive advantage is defined as the ability to stay ahead of present or potential competition. This is typically done by evaluating strengths and weaknesses of competitors and seeing where you can fill in the gap or step up and improve.\nCompanies develop a competitive edge when they produce attributes that allow them to outperform their competitors.\nHere are seven ways companies and individuals can create an edge.\n• Cost Leadership Strategy\n• Differentiation Strategy\n• Innovative Strategy\n• Operational Effectiveness Strategy\n• Technology Based Competitive Strategy\n• Adaptability Competitive Advantage\n• The Information Advantage\n\nThe most immediately understandable competitive edges are those based on proprietary technology. A patent, an algorithm, even deeply entrenched know-how can be solid competitive edges. In services, however, the edge can be as simple as having the phone number 1 (800) SOFTWARE, which is an actual case. A successful company was built around that phone number."
            },
            new InstructionItem(){
                section ="Strategy Summary",
                instruction ="Marketing strategy is the section of your business plan that outlines your overall game plan for finding clients and customers for your business. Sometimes marketing strategy is confused with a marketing plan, but they are different.\n\nMarketing strategy focuses on what you want to achieve for your business and marketing efforts.\nMarketing plan details how you'll achieve those goals.\nA good marketing strategy incorporates what you know about how your business fits into the market and the 5 Ps of marketing to develop the tactics and actions that will achieve your marketing objectives.\n\nBefore writing your marketing strategy, you need to know how your product or service benefits others and how it's unique (unique selling proposition) to other businesses in the marketplace. Further, you need to do market research to understand your competition, your target market, and other factors that will impact your ability to reach and entice people to your business."
            },
            new InstructionItem(){
                section ="Sales Strategy",
                instruction ="A sales strategy is an approach to selling that allows an organization’s sales force to position the company and its product(s) to target customers in a meaningful, differentiated way. Most strategies involve a detailed plan of best practices and processes set out by management.\nThere are two primary types of sales strategies: inbound and outbound. In outbound sales — the legacy system of most sales teams — companies base their sales strategy on seller actions. They rely on manually-entered data to monitor the sales pipeline and coach their salespeople, and they run sales and marketing independently, creating a disjointed experience for buyers.\n\nIn inbound sales — the modern methodology for sales teams — companies base their sales process on buyer actions. They automatically capture seller and buyer data to monitor the pipeline and coach salespeople, and they align sales and marketing, creating a seamless experience for buyers."
            },
            new InstructionItem(){
                section ="Explain Sales Forecast",
                instruction ="Use this topic to explain the Sales Forecast table. Your annual sales forecast prints with the topic and the monthlies are in the appendix. \nAdditional Detail\nEmphasize important points and explain assumptions.\n\n• What growth rates are you expecting for the more important lines, and what growth rates in units, and in pounds?\n• Why are you projecting your sales at this level? Why not less or more?\n• What are the main driving forces behind the sales forecast?\n• How does it relate to your market analysis, your main target segments, your sales strategy and marketing strategy?\n• Is your sales forecast believable? Why?\n• What events might turn the sales forecast downward?\n• What kind of things are you assuming will happen to make sure the sales happen?"
            },
            new InstructionItem(){
                section ="Competitive Study",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Business Analysis",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Developments Requirements",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Website Strategy",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Market Segmentation",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Analysis Table",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Threats",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Opportunities",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Weaknesses",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Strengths",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Market Summary",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Product & Service Summary",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Service Summary",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Product Summary",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Company Expenditure",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Start Up Investment",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Ownership",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Company Summary",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Mission",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            },
            new InstructionItem(){
                section ="Objectives",
                instruction ="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras porta ut dolor at scelerisque. Curabitur quis volutpat lectus, vitae vulputate quam. Fusce tincidunt sem vel metus malesuada, quis rhoncus nulla eleifend. Nulla laoreet dolor lacus, viverra molestie nisl dignissim eget. Integer at cursus lacus, nec aliquet mi. Morbi eget massa quis nisi dapibus posuere. Fusce ac orci nunc. Sed in eros mauris. Fusce accumsan mollis imperdiet. Curabitur pharetra eros nec purus imperdiet dapibus. Praesent mollis mauris neque, sit amet tempor quam tristique ut. Duis risus mauris, gravida sit amet risus ut, hendrerit pulvinar sem. Aliquam pretium vel ante hendrerit euismod. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In mollis, turpis eget rhoncus tempus, risus magna sollicitudin felis, ut facilisis lorem turpis sit amet tortor."
            }
        };
    }
}
