using BP.Samples.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BP.Samples
{
    public class SampleData
    {
        public List<SampleItem> items = new List<SampleItem>()
        {
            new SampleItem(){id=1,section="Objectives",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Objectives",content=""},
            new SampleItem(){id=3,section="Objectives",content=""},
            new SampleItem(){id=4,section="Objectives",content=""},
            new SampleItem(){id=5,section="Objectives",content=""},
            new SampleItem(){id=6,section="Objectives",content=""},
            new SampleItem(){id=7,section="Objectives",content=""},
            new SampleItem(){id=8,section="Objectives",content=""},
            new SampleItem(){id=9,section="Objectives",content=""},
            new SampleItem(){id=10,section="Objectives",content=""},
            new SampleItem(){id=11,section="Objectives",content=""},
            new SampleItem(){id=12,section="Objectives",content=""},
            new SampleItem(){id=13,section="Objectives",content=""},
            new SampleItem(){id=14,section="Objectives",content=""},
            new SampleItem(){id=15,section="Objectives",content=""},
            new SampleItem(){id=1,section="Mission",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Mission",content=""},
            new SampleItem(){id=3,section="Mission",content=""},
            new SampleItem(){id=4,section="Mission",content=""},
            new SampleItem(){id=5,section="Mission",content=""},
            new SampleItem(){id=6,section="Mission",content=""},
            new SampleItem(){id=7,section="Mission",content=""},
            new SampleItem(){id=8,section="Mission",content=""},
            new SampleItem(){id=9,section="Mission",content=""},
            new SampleItem(){id=10,section="Mission",content=""},
            new SampleItem(){id=11,section="Mission",content=""},
            new SampleItem(){id=12,section="Mission",content=""},
            new SampleItem(){id=13,section="Mission",content=""},
            new SampleItem(){id=14,section="Mission",content=""},
            new SampleItem(){id=15,section="Mission",content=""},
            new SampleItem(){id=1,section="Company Summary",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Company Summary",content=""},
            new SampleItem(){id=3,section="Company Summary",content=""},
            new SampleItem(){id=4,section="Company Summary",content=""},
            new SampleItem(){id=5,section="Company Summary",content=""},
            new SampleItem(){id=6,section="Company Summary",content=""},
            new SampleItem(){id=7,section="Company Summary",content=""},
            new SampleItem(){id=8,section="Company Summary",content=""},
            new SampleItem(){id=9,section="Company Summary",content=""},
            new SampleItem(){id=10,section="Company Summary",content=""},
            new SampleItem(){id=11,section="Company Summary",content=""},
            new SampleItem(){id=12,section="Company Summary",content=""},
            new SampleItem(){id=13,section="Company Summary",content=""},
            new SampleItem(){id=14,section="Company Summary",content=""},
            new SampleItem(){id=15,section="Company Summary",content=""},
            new SampleItem(){id=1,section="Ownership",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Ownership",content=""},
            new SampleItem(){id=3,section="Ownership",content=""},
            new SampleItem(){id=4,section="Ownership",content=""},
            new SampleItem(){id=5,section="Ownership",content=""},
            new SampleItem(){id=6,section="Ownership",content=""},
            new SampleItem(){id=7,section="Ownership",content=""},
            new SampleItem(){id=8,section="Ownership",content=""},
            new SampleItem(){id=9,section="Ownership",content=""},
            new SampleItem(){id=10,section="Ownership",content=""},
            new SampleItem(){id=11,section="Ownership",content=""},
            new SampleItem(){id=12,section="Ownership",content=""},
            new SampleItem(){id=13,section="Ownership",content=""},
            new SampleItem(){id=14,section="Ownership",content=""},
            new SampleItem(){id=15,section="Ownership",content=""},
            new SampleItem(){id=1,section="Product Summary",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=6,section="Product Summary",content=""},
            new SampleItem(){id=7,section="Product Summary",content=""},
            new SampleItem(){id=8,section="Product Summary",content=""},
            new SampleItem(){id=9,section="Product Summary",content=""},
            new SampleItem(){id=10,section="Product Summary",content=""},
            new SampleItem(){id=2,section="Service Summary",content=""},
            new SampleItem(){id=3,section="Service Summary",content=""},
            new SampleItem(){id=4,section="Service Summary",content=""},
            new SampleItem(){id=5,section="Service Summary",content=""},
            new SampleItem(){id=11,section="Product & Service Summary",content=""},
            new SampleItem(){id=12,section="Product & Service Summary",content=""},
            new SampleItem(){id=13,section="Product & Service Summary",content=""},
            new SampleItem(){id=14,section="Product & Service Summary",content=""},
            new SampleItem(){id=15,section="Product & Service Summary",content=""},
            new SampleItem(){id=1,section="Market Summary",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Market Summary",content=""},
            new SampleItem(){id=3,section="Market Summary",content=""},
            new SampleItem(){id=4,section="Market Summary",content=""},
            new SampleItem(){id=5,section="Market Summary",content=""},
            new SampleItem(){id=6,section="Market Summary",content=""},
            new SampleItem(){id=7,section="Market Summary",content=""},
            new SampleItem(){id=8,section="Market Summary",content=""},
            new SampleItem(){id=9,section="Market Summary",content=""},
            new SampleItem(){id=10,section="Market Summary",content=""},
            new SampleItem(){id=11,section="Market Summary",content=""},
            new SampleItem(){id=12,section="Market Summary",content=""},
            new SampleItem(){id=13,section="Market Summary",content=""},
            new SampleItem(){id=14,section="Market Summary",content=""},
            new SampleItem(){id=15,section="Market Summary",content=""},
            new SampleItem(){id=1,section="Strengths",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Strengths",content=""},
            new SampleItem(){id=3,section="Strengths",content=""},
            new SampleItem(){id=4,section="Strengths",content=""},
            new SampleItem(){id=5,section="Strengths",content=""},
            new SampleItem(){id=1,section="Weaknesses",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Weaknesses",content=""},
            new SampleItem(){id=3,section="Weaknesses",content=""},
            new SampleItem(){id=4,section="Weaknesses",content=""},
            new SampleItem(){id=5,section="Weaknesses",content=""},
            new SampleItem(){id=1,section="Opportunities",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Opportunities",content=""},
            new SampleItem(){id=3,section="Opportunities",content=""},
            new SampleItem(){id=4,section="Opportunities",content=""},
            new SampleItem(){id=5,section="Opportunities",content=""},
            new SampleItem(){id=1,section="Threats",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Threats",content=""},
            new SampleItem(){id=3,section="Threats",content=""},
            new SampleItem(){id=4,section="Threats",content=""},
            new SampleItem(){id=5,section="Threats",content=""}, 
            new SampleItem(){id=1,section="Market Segmentation",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Market Segmentation",content=""},
            new SampleItem(){id=3,section="Market Segmentation",content=""},
            new SampleItem(){id=4,section="Market Segmentation",content=""},
            new SampleItem(){id=5,section="Market Segmentation",content=""},
            new SampleItem(){id=6,section="Market Segmentation",content=""},
            new SampleItem(){id=7,section="Market Segmentation",content=""},
            new SampleItem(){id=8,section="Market Segmentation",content=""},
            new SampleItem(){id=9,section="Market Segmentation",content=""},
            new SampleItem(){id=10,section="Market Segmentation",content=""},
            new SampleItem(){id=11,section="Market Segmentation",content=""},
            new SampleItem(){id=12,section="Market Segmentation",content=""},
            new SampleItem(){id=13,section="Market Segmentation",content=""},
            new SampleItem(){id=14,section="Market Segmentation",content=""},
            new SampleItem(){id=15,section="Market Segmentation",content=""},
            new SampleItem(){id=1,section="Website Strategy",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Website Strategy",content=""},
            new SampleItem(){id=3,section="Website Strategy",content=""},
            new SampleItem(){id=4,section="Website Strategy",content=""},
            new SampleItem(){id=5,section="Website Strategy",content=""},
            new SampleItem(){id=1,section="Developments Requirements",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Developments Requirements",content=""},
            new SampleItem(){id=3,section="Developments Requirements",content=""},
            new SampleItem(){id=4,section="Developments Requirements",content=""},
            new SampleItem(){id=5,section="Developments Requirements",content=""},
            new SampleItem(){id=1,section="Business Analysis",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Business Analysis",content=""},
            new SampleItem(){id=3,section="Business Analysis",content=""},
            new SampleItem(){id=4,section="Business Analysis",content=""},
            new SampleItem(){id=5,section="Business Analysis",content=""},
            new SampleItem(){id=6,section="Business Analysis",content=""},
            new SampleItem(){id=7,section="Business Analysis",content=""},
            new SampleItem(){id=8,section="Business Analysis",content=""},
            new SampleItem(){id=9,section="Business Analysis",content=""},
            new SampleItem(){id=10,section="Business Analysis",content=""},
            new SampleItem(){id=11,section="Business Analysis",content=""},
            new SampleItem(){id=12,section="Business Analysis",content=""},
            new SampleItem(){id=13,section="Business Analysis",content=""},
            new SampleItem(){id=14,section="Business Analysis",content=""},
            new SampleItem(){id=15,section="Business Analysis",content=""},
            new SampleItem(){id=1,section="Competitive Study",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Competitive Study",content=""},
            new SampleItem(){id=3,section="Competitive Study",content=""},
            new SampleItem(){id=4,section="Competitive Study",content=""},
            new SampleItem(){id=5,section="Competitive Study",content=""},
            new SampleItem(){id=6,section="Competitive Study",content=""},
            new SampleItem(){id=7,section="Competitive Study",content=""},
            new SampleItem(){id=8,section="Competitive Study",content=""},
            new SampleItem(){id=9,section="Competitive Study",content=""},
            new SampleItem(){id=10,section="Competitive Study",content=""},
            new SampleItem(){id=11,section="Competitive Study",content=""},
            new SampleItem(){id=12,section="Competitive Study",content=""},
            new SampleItem(){id=13,section="Competitive Study",content=""},
            new SampleItem(){id=14,section="Competitive Study",content=""},
            new SampleItem(){id=15,section="Competitive Study",content=""},
            new SampleItem(){id=1,section="Sales Strategy",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Sales Strategy",content=""},
            new SampleItem(){id=3,section="Sales Strategy",content=""},
            new SampleItem(){id=4,section="Sales Strategy",content=""},
            new SampleItem(){id=5,section="Sales Strategy",content=""},
            new SampleItem(){id=6,section="Sales Strategy",content=""},
            new SampleItem(){id=7,section="Sales Strategy",content=""},
            new SampleItem(){id=8,section="Sales Strategy",content=""},
            new SampleItem(){id=9,section="Sales Strategy",content=""},
            new SampleItem(){id=10,section="Sales Strategy",content=""},
            new SampleItem(){id=11,section="Sales Strategy",content=""},
            new SampleItem(){id=12,section="Sales Strategy",content=""},
            new SampleItem(){id=13,section="Sales Strategy",content=""},
            new SampleItem(){id=14,section="Sales Strategy",content=""},
            new SampleItem(){id=15,section="Sales Strategy",content=""}, 
            new SampleItem(){id=1,section="Explain Sales Forecast",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=3,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=4,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=5,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=6,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=7,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=8,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=9,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=10,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=11,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=12,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=13,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=14,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=15,section="Explain Sales Forecast",content=""},
            new SampleItem(){id=1,section="Strategy Summary",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Strategy Summary",content=""},
            new SampleItem(){id=3,section="Strategy Summary",content=""},
            new SampleItem(){id=4,section="Strategy Summary",content=""},
            new SampleItem(){id=5,section="Strategy Summary",content=""},
            new SampleItem(){id=6,section="Strategy Summary",content=""},
            new SampleItem(){id=7,section="Strategy Summary",content=""},
            new SampleItem(){id=8,section="Strategy Summary",content=""},
            new SampleItem(){id=9,section="Strategy Summary",content=""},
            new SampleItem(){id=10,section="Strategy Summary",content=""},
            new SampleItem(){id=11,section="Strategy Summary",content=""},
            new SampleItem(){id=12,section="Strategy Summary",content=""},
            new SampleItem(){id=13,section="Strategy Summary",content=""},
            new SampleItem(){id=14,section="Strategy Summary",content=""},
            new SampleItem(){id=15,section="Strategy Summary",content=""},
            new SampleItem(){id=1,section="Competitive Edge",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Competitive Edge",content=""},
            new SampleItem(){id=3,section="Competitive Edge",content=""},
            new SampleItem(){id=4,section="Competitive Edge",content=""},
            new SampleItem(){id=5,section="Competitive Edge",content=""},
            new SampleItem(){id=6,section="Competitive Edge",content=""},
            new SampleItem(){id=7,section="Competitive Edge",content=""},
            new SampleItem(){id=8,section="Competitive Edge",content=""},
            new SampleItem(){id=9,section="Competitive Edge",content=""},
            new SampleItem(){id=10,section="Competitive Edge",content=""},
            new SampleItem(){id=11,section="Competitive Edge",content=""},
            new SampleItem(){id=12,section="Competitive Edge",content=""},
            new SampleItem(){id=13,section="Competitive Edge",content=""},
            new SampleItem(){id=14,section="Competitive Edge",content=""},
            new SampleItem(){id=15,section="Competitive Edge",content=""},
            new SampleItem(){id=1,section="Financial Summary",content="JJB aims to offer its products at a competitive price to meet the demand of the middle-to higher-income local market area residents and tourists."},
            new SampleItem(){id=2,section="Financial Summary",content=""},
            new SampleItem(){id=3,section="Financial Summary",content=""},
            new SampleItem(){id=4,section="Financial Summary",content=""},
            new SampleItem(){id=5,section="Financial Summary",content=""},
            new SampleItem(){id=6,section="Financial Summary",content=""},
            new SampleItem(){id=7,section="Financial Summary",content=""},
            new SampleItem(){id=8,section="Financial Summary",content=""},
            new SampleItem(){id=9,section="Financial Summary",content=""},
            new SampleItem(){id=10,section="Financial Summary",content=""},
            new SampleItem(){id=11,section="Financial Summary",content=""},
            new SampleItem(){id=12,section="Financial Summary",content=""},
            new SampleItem(){id=13,section="Financial Summary",content=""},
            new SampleItem(){id=14,section="Financial Summary",content=""},
            new SampleItem(){id=15,section="Financial Summary",content=""},
            
        };
    }
}
